// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, calories, protein_g, carbs_g, fat_g, is_frequent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, calories, protein_g, carbs_g, fat_g, created_at, is_frequent
`

type CreateFoodParams struct {
	Name       string
	Calories   pgtype.Numeric
	ProteinG   pgtype.Numeric
	CarbsG     pgtype.Numeric
	FatG       pgtype.Numeric
	IsFrequent bool
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.IsFrequent,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.CreatedAt,
		&i.IsFrequent,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM foods WHERE id = $1
`

func (q *Queries) DeleteFood(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFood, id)
	return err
}

const getFood = `-- name: GetFood :one
SELECT id, name, calories, protein_g, carbs_g, fat_g, created_at, is_frequent FROM foods WHERE id = $1
`

func (q *Queries) GetFood(ctx context.Context, id int32) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.CreatedAt,
		&i.IsFrequent,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT id, name, calories, protein_g, carbs_g, fat_g, created_at, is_frequent FROM foods
WHERE $1::boolean IS NULL
   OR is_frequent = $1
ORDER BY id
`

func (q *Queries) ListFoods(ctx context.Context, isFrequent pgtype.Bool) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoods, isFrequent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.CreatedAt,
			&i.IsFrequent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFoodFrequent = `-- name: SetFoodFrequent :one
UPDATE foods SET is_frequent = $2 WHERE id = $1
RETURNING id, name, calories, protein_g, carbs_g, fat_g, created_at, is_frequent
`

type SetFoodFrequentParams struct {
	ID         int32
	IsFrequent bool
}

func (q *Queries) SetFoodFrequent(ctx context.Context, arg SetFoodFrequentParams) (Food, error) {
	row := q.db.QueryRow(ctx, setFoodFrequent, arg.ID, arg.IsFrequent)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.CreatedAt,
		&i.IsFrequent,
	)
	return i, err
}
