// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :one

INSERT INTO foods (name, calories, protein_g, carbs_g, fat_g)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, calories, protein_g, carbs_g, fat_g, created_at
`

type CreateFoodParams struct {
	Name     string
	Calories pgtype.Numeric
	ProteinG pgtype.Numeric
	CarbsG   pgtype.Numeric
	FatG     pgtype.Numeric
}

// db/queries/foods.sql
func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM foods WHERE id = $1
`

func (q *Queries) DeleteFood(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFood, id)
	return err
}

const getFood = `-- name: GetFood :one
SELECT id, name, calories, protein_g, carbs_g, fat_g, created_at FROM foods WHERE id = $1
`

func (q *Queries) GetFood(ctx context.Context, id int32) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.CreatedAt,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT id, name, calories, protein_g, carbs_g, fat_g, created_at FROM foods ORDER BY id
`

func (q *Queries) ListFoods(ctx context.Context) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
