// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLogEntry = `-- name: CreateLogEntry :one
INSERT INTO log_entries (food_id, food_name, calories, protein_g, carbs_g, fat_g, multiplier, logged_at)
SELECT $1, f.name, f.calories, f.protein_g, f.carbs_g, f.fat_g, $2,
       COALESCE($3::date, CURRENT_DATE)
FROM foods f
WHERE f.id = $1
RETURNING id, food_id, multiplier, logged_at, created_at, food_name, calories, protein_g, carbs_g, fat_g
`

type CreateLogEntryParams struct {
	FoodID     pgtype.Int4
	Multiplier pgtype.Numeric
	LoggedAt   pgtype.Date
}

func (q *Queries) CreateLogEntry(ctx context.Context, arg CreateLogEntryParams) (LogEntry, error) {
	row := q.db.QueryRow(ctx, createLogEntry, arg.FoodID, arg.Multiplier, arg.LoggedAt)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.FoodID,
		&i.Multiplier,
		&i.LoggedAt,
		&i.CreatedAt,
		&i.FoodName,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
	)
	return i, err
}

const deleteLogEntry = `-- name: DeleteLogEntry :exec
DELETE FROM log_entries WHERE id = $1
`

func (q *Queries) DeleteLogEntry(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLogEntry, id)
	return err
}

const getLogEntry = `-- name: GetLogEntry :one
SELECT id, food_id, multiplier, logged_at, created_at, food_name, calories, protein_g, carbs_g, fat_g FROM log_entries where id = $1
`

func (q *Queries) GetLogEntry(ctx context.Context, id int32) (LogEntry, error) {
	row := q.db.QueryRow(ctx, getLogEntry, id)
	var i LogEntry
	err := row.Scan(
		&i.ID,
		&i.FoodID,
		&i.Multiplier,
		&i.LoggedAt,
		&i.CreatedAt,
		&i.FoodName,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
	)
	return i, err
}

const getMacroTotalsByDate = `-- name: GetMacroTotalsByDate :one
SELECT
    COALESCE(SUM(calories * multiplier), 0)::numeric AS calories,
    COALESCE(SUM(protein_g * multiplier), 0)::numeric AS protein_g,
    COALESCE(SUM(carbs_g * multiplier), 0)::numeric AS carbs_g,
    COALESCE(SUM(fat_g * multiplier), 0)::numeric AS fat_g
FROM log_entries
WHERE logged_at = $1
`

type GetMacroTotalsByDateRow struct {
	Calories pgtype.Numeric
	ProteinG pgtype.Numeric
	CarbsG   pgtype.Numeric
	FatG     pgtype.Numeric
}

func (q *Queries) GetMacroTotalsByDate(ctx context.Context, loggedAt pgtype.Date) (GetMacroTotalsByDateRow, error) {
	row := q.db.QueryRow(ctx, getMacroTotalsByDate, loggedAt)
	var i GetMacroTotalsByDateRow
	err := row.Scan(
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
	)
	return i, err
}

const listLogEntries = `-- name: ListLogEntries :many
SELECT id, food_id, multiplier, logged_at, created_at, food_name, calories, protein_g, carbs_g, fat_g FROM log_entries ORDER BY logged_at DESC, id
`

func (q *Queries) ListLogEntries(ctx context.Context) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, listLogEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.FoodID,
			&i.Multiplier,
			&i.LoggedAt,
			&i.CreatedAt,
			&i.FoodName,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEntriesByDate = `-- name: ListLogEntriesByDate :many
SELECT id, food_id, multiplier, logged_at, created_at, food_name, calories, protein_g, carbs_g, fat_g FROM log_entries
WHERE logged_at = $1
ORDER BY id
`

func (q *Queries) ListLogEntriesByDate(ctx context.Context, loggedAt pgtype.Date) ([]LogEntry, error) {
	rows, err := q.db.Query(ctx, listLogEntriesByDate, loggedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEntry
	for rows.Next() {
		var i LogEntry
		if err := rows.Scan(
			&i.ID,
			&i.FoodID,
			&i.Multiplier,
			&i.LoggedAt,
			&i.CreatedAt,
			&i.FoodName,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
