// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	ID        int32
	Name      string
	Calories  pgtype.Numeric
	ProteinG  pgtype.Numeric
	CarbsG    pgtype.Numeric
	FatG      pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type LogEntry struct {
	ID         int32
	FoodID     int32
	Multiplier pgtype.Numeric
	LoggedAt   pgtype.Date
	CreatedAt  pgtype.Timestamptz
}
